# Generated by Django 3.1.2 on 2020-10-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updown', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='title',
        ),
    ]
